apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Anilreddy2309/devops-projects
    targetRevision: HEAD
    path: week05-gitops/clusters/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
